authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    path('register/', views.AuthorRegister.as_view(), name="register_author"),
    path('login/', views.AuthorLogin.as_view(), name="login_author"),
    path('logout/', views.AuthorLogout.as_view(), name="logout_author")
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('profile/<int:id>/', views.home, name="home"),
    path('dashboard/follows/<int:id>/', views.list_follows_or_following,
         {'type_': 'follows'}, name="list_follows"),

    path('dashboard/following/<int:id>/', views.list_follows_or_following,
         {'type_': 'following'}, name="list_following"),

    path('dashboard/unfollow_user/<int:id>/', views.unfollow_or_unfollowing,
         {'type_': 'unfollow'}, name="unfollow_user"),

    path('dashboard/unfollowing_user/<int:id>/',
         views.unfollow_or_unfollowing,
         {'type_': 'unfollowing'}, name="unfollowing_user"),

    path('follow/<int:id>/', views.follow_user_system,
         name="follow_user_system"),
    path('unfollow/<int:id>/', views.unfollow_user_system,
         name="unfollow_user_system"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social_echo.urls')),
    path('authors/', include('authors.urls')),
    path('dashboard/', include('dashboard.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

social_echo/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from . import views

post_api_route = SimpleRouter()
post_api_route.register(
    'api',
    views.PostAPIModelViewSet,
    basename='post_api'
)

app_name = 'social_echo'

urlpatterns = [
     path('', views.PostListViewHome.as_view(), name="home"),

     path('create_post/',
          views.PostCreateView.as_view(),
          name="create_post"
          ),
     path('edit_post/<int:pk>/',
          views.PostUpdateView.as_view(),
          name="edit_post"
          ),
     path('delete_post/<int:pk>/',
          views.PostDeleteView.as_view(),
          name="delete_post"
          ),
     path('view_post/<int:pk>/',
          views.ViewPostDetailView.as_view(),
          name="view_post"
          ),

     path(
         'api/token/',
         TokenObtainPairView.as_view(),
         name='token_obtain_pair'
     ),
     path(
         'api/token/refresh/',
         TokenRefreshView.as_view(),
         name='token_refresh'
     ),
     path(
         'api/token/verify/',
         TokenVerifyView.as_view(),
         name='token_verify'
     ),
]

urlpatterns += post_api_route.urls

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404,
)
from social_echo.models import Posts, AuthorUser
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.contrib.auth.models import User


def home(request, id):
    posts = Posts.objects.filter(author=id)

    author = AuthorUser.objects.filter(author=id).first()

    you = AuthorUser.objects.filter(author=request.user).first()

    user_followings = you.following.all()

    user = None

    if not posts:
        raise Http404()
    else:
        user = posts[0].author

    try:
        cover = author.cover
        follows = author.follows.count()
        following = author.following.count()

    except AttributeError:
        cover = 'media/user/base/base_cover.jpeg'
        follows = 0
        following = 0

    return render(request, 'dashboard/pages/dashboard.html', context={
        'posts': posts,
        'user': user,
        'cover': cover,
        'follows': follows,
        'following': following,
        'user_followings': user_followings
    })


def list_follows_or_following(request, id, type_):
    author = get_object_or_404(AuthorUser, id=id)

    owner = False

    if str(request.user) == str(author):
        owner = True

    if type_ == 'follows':
        users = author.follows.all()
    elif type_ == 'following':
        users = author.following.all()

    return render(request, 'dashboard/pages/list_follows_following.html', context={ # noqa E501
        'users': users,
        'owner': owner,
        'type_': type_,
    })


@login_required
def unfollow_or_unfollowing(request, id, type_):
    # Deixar só como post
    author = AuthorUser.objects.filter(author=request.user).first()

    unfollow_user = get_object_or_404(User, id=id)

    if type_ == 'unfollow':
        if unfollow_user in author.follows.all():
            author.follows.remove(unfollow_user)

    elif type_ == 'unfollowing':
        if unfollow_user in author.following.all():
            author.following.remove(unfollow_user)

    return redirect('social_echo:home')


@login_required
def follow_user_system(request, id):
    author = get_object_or_404(AuthorUser, author=request.user)
    author_for_follow = get_object_or_404(AuthorUser, id=id)

    author.following.add(author_for_follow.author)
    author_for_follow.follows.add(author.author)

    return redirect('dashboard:home', id=id)


@login_required
def unfollow_user_system(request, id):
    author = get_object_or_404(AuthorUser, author=request.user)
    author_for_follow = get_object_or_404(AuthorUser, id=id)

    author.following.remove(author_for_follow.author)
    author_for_follow.follows.remove(author.author)

    return redirect('dashboard:home', id=id)

dashboard/templates/dashboard/pages/dashboard.html
{% extends "global/pages/base.html" %}

{% block content %}
    <div class="dashboard-user-container">
        <div class="dashboard-user">
            {% if cover %}
                <p><img src="{{ cover.url }}" alt="" class="image"></p>
            {% endif %}
            <p>{{ user }}</p>

            <div class="follow_following_dashboard">
                <a href="{% url 'dashboard:list_follows' posts.0.author.id %}">Seguidores: {{ follows }}</a>
                <a href="{% url 'dashboard:list_following' posts.0.author.id %}">Seguindo: {{ following }}</a>
            </div>
            
            {% if request.user.is_authenticated and request.user != user %}
                {% if not user in user_followings %}
                    <a href="{% url 'dashboard:follow_user_system' posts.0.author.id%}" class="follow-btn">Seguir</a>
                {% else %}
                    <a href="{% url 'dashboard:unfollow_user_system' posts.0.author.id%}" class="unfollow-btn">Deixar de seguir</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <div class="main-dashboard-container">
        {% for post in posts %}
            <div>
                <div class="dashboard-container">
                    <div class="dashboard-title">
                        <a href="{% url 'social_echo:edit_post' post.id %}">{{ post.title }}</a>
                    </div>
                    {% if request.user == post.author %}
                        <div class="dashboard-container-button">
                            <a class="button button-dashboard" href="{% url 'social_echo:edit_post' post.id %}">Editar</a>
                            <a class="button button-dashboard" href="{% url 'social_echo:delete_post' post.id %}">Deletar</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

dashboard/templates/dashboard/pages/list_follows_following.html
{% extends "global/pages/base.html" %}

{% block content %}
    <div class="main-ff-container">
        {% for user in users %}
            <div>
                <div class="ff-container">
                    <div class="ff-title">
                        <p>{{ user }}</p>
                    </div>
                    {% if owner %}
                        <div class="ff-container-button">
                            {% if type_ == 'follows' %}
                                <a class="button button-ff" href="{% url 'dashboard:unfollow_user' user.id %}">Deletar</a>
                            {% elif type_ == 'following' %}
                                <a class="button button-ff" href="{% url 'dashboard:unfollowing_user' user.id %}">Deletar</a>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}