authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    path('register/', views.AuthorRegister.as_view(), name="register_author"),
    path('login/', views.AuthorLogin.as_view(), name="login_author"),
    path('logout/', views.AuthorLogout.as_view(), name="logout_author")
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('profile/<int:id>/', views.home, name="home"),
    path('dashboard/follows/<int:id>/', views.list_follows_or_following,
         {'type_': 'follows'}, name="list_follows"),

    path('dashboard/following/<int:id>/', views.list_follows_or_following,
         {'type_': 'following'}, name="list_following"),

    path('dashboard/unfollow_user/<int:id>/', views.unfollow_or_unfollowing,
         {'type_': 'unfollow'}, name="unfollow_user"),

    path('dashboard/unfollowing_user/<int:id>/',
         views.unfollow_or_unfollowing,
         {'type_': 'unfollowing'}, name="unfollowing_user"),

    path('follow/<int:id>/', views.follow_user_system,
         name="follow_user_system"),
    path('unfollow/<int:id>/', views.unfollow_user_system,
         name="unfollow_user_system"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social_echo.urls')),
    path('authors/', include('authors.urls')),
    path('dashboard/', include('dashboard.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

social_echo/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from . import views

post_api_route = SimpleRouter()
post_api_route.register(
    'api',
    views.PostAPIModelViewSet,
    basename='post_api'
)

app_name = 'social_echo'

urlpatterns = [
     path('', views.PostListViewHome.as_view(), name="home"),

     path('create_post/',
          views.PostCreateView.as_view(),
          name="create_post"
          ),
     path('edit_post/<int:pk>/',
          views.PostUpdateView.as_view(),
          name="edit_post"
          ),
     path('delete_post/<int:pk>/',
          views.PostDeleteView.as_view(),
          name="delete_post"
          ),
     path('view_post/<int:pk>/',
          views.ViewPostDetailView.as_view(),
          name="view_post"
          ),

     path(
         'api/token/',
         TokenObtainPairView.as_view(),
         name='token_obtain_pair'
     ),
     path(
         'api/token/refresh/',
         TokenRefreshView.as_view(),
         name='token_refresh'
     ),
     path(
         'api/token/verify/',
         TokenVerifyView.as_view(),
         name='token_verify'
     ),
]

urlpatterns += post_api_route.urls

dashboard/models.py
from django.db import models

# Create your models here.

social_echo/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from authors.models import AuthorUser


class Posts(models.Model):
    title = models.CharField(max_length=55)
    message = models.CharField(max_length=155)
    cover = models.ImageField(upload_to='media/%Y/%m/%d/',
                              blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    author_cover = models.ForeignKey(
        AuthorUser, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f'{self.message}'

    def get_absolute_url(self):
        return reverse('social_echo:view_post', args=(self.id,))

    def get_edit_url(self):
        return reverse('social_echo:edit_post', args=(self.id,))

    def get_delete_url(self):
        return reverse('social_echo:delete_post', args=(self.id,))

social_echo/forms.py
from django import forms
from .models import Posts


class CreatePost(forms.ModelForm):
    class Meta:
        model = Posts
        fields = [
            'title',
            'message',
            'cover',
        ]

dashboard/views.py
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404,
)
from social_echo.models import Posts, AuthorUser
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.contrib.auth.models import User


def home(request, id):
    posts = Posts.objects.filter(author=id)

    author = AuthorUser.objects.filter(author=id).first()

    you = AuthorUser.objects.filter(author=request.user).first()

    user_followings = you.following.all()

    user = None

    if not posts:
        raise Http404()
    else:
        user = posts[0].author

    try:
        cover = author.cover
        follows = author.follows.count()
        following = author.following.count()

    except AttributeError:
        cover = 'media/user/base/base_cover.jpeg'
        follows = 0
        following = 0

    return render(request, 'dashboard/pages/dashboard.html', context={
        'posts': posts,
        'user': user,
        'cover': cover,
        'follows': follows,
        'following': following,
        'user_followings': user_followings
    })


def list_follows_or_following(request, id, type_):
    author = get_object_or_404(AuthorUser, id=id)

    owner = False

    if str(request.user) == str(author):
        owner = True

    if type_ == 'follows':
        users = author.follows.all()
    elif type_ == 'following':
        users = author.following.all()

    return render(request, 'dashboard/pages/list_follows_following.html', context={ # noqa E501
        'users': users,
        'owner': owner,
        'type_': type_,
    })


@login_required
def unfollow_or_unfollowing(request, id, type_):
    # Deixar só como post
    author = AuthorUser.objects.filter(author=request.user).first()

    unfollow_user = get_object_or_404(User, id=id)

    if type_ == 'unfollow':
        if unfollow_user in author.follows.all():
            author.follows.remove(unfollow_user)

    elif type_ == 'unfollowing':
        if unfollow_user in author.following.all():
            author.following.remove(unfollow_user)

    return redirect('social_echo:home')


@login_required
def follow_user_system(request, id):
    author = get_object_or_404(AuthorUser, author=request.user)
    author_for_follow = get_object_or_404(AuthorUser, id=id)

    author.following.add(author_for_follow.author)
    author_for_follow.follows.add(author.author)

    return redirect('dashboard:home', id=id)


@login_required
def unfollow_user_system(request, id):
    author = get_object_or_404(AuthorUser, author=request.user)
    author_for_follow = get_object_or_404(AuthorUser, id=id)

    author.following.remove(author_for_follow.author)
    author_for_follow.follows.remove(author.author)

    return redirect('dashboard:home', id=id)

social_echo/views/all.py
from django.shortcuts import (
    render,
    get_object_or_404,
)
from social_echo.models import Posts
from django.views.generic import ListView
from django.http import Http404


class PostListView(ListView):
    model = Posts
    template_name = 'social_echo/pages/home.html'
    context_object_name = 'posts'
    paginate_by = 5


class PostListViewHome(PostListView):
    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)

        queryset = queryset.all().order_by('-id')

        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context.update({
            'title': 'Home',
        })

        return context


def home(request):
    posts = Posts.objects.all().order_by('-id')

    return render(request, 'social_echo/pages/home.html', context={
        'title': 'Home',
        'posts': posts
    })


def view_post(request, id):
    posts = get_object_or_404(Posts, id=id)

    if not posts.cover:
        raise Http404()

    return render(request, 'social_echo/pages/view_page.html', context={
        'title': 'View Page',
        'posts': posts
    })

social_echo/views/api.py
from rest_framework.pagination import PageNumberPagination
from rest_framework.permissions import IsAuthenticated
from rest_framework.viewsets import ModelViewSet

from social_echo.models import Posts
from social_echo.serializers import PostSerializer


class PostAPIPagination(PageNumberPagination):
    page_size = 10


class PostAPIModelViewSet(ModelViewSet):
    queryset = Posts.objects.all()
    serializer_class = PostSerializer
    pagination_class = PostAPIPagination
    permission_classes = [IsAuthenticated,]

social_echo/views/crud_home.py
from social_echo.models import Posts
from django.views.generic import ListView, DetailView


class PostListView(ListView):
    model = Posts
    template_name = 'social_echo/pages/home.html'
    context_object_name = 'posts'
    paginate_by = 5


class PostListViewHome(PostListView):
    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)

        queryset = queryset.all().order_by('-id')

        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context.update({
            'title': 'Home',
        })

        return context


class ViewPostDetailView(DetailView):
    template_name = 'social_echo/pages/view_page.html'
    model = Posts
    context_object_name = 'post'

social_echo/views/crud_post.py
from social_echo.models import Posts, AuthorUser
from social_echo.forms import CreatePost
from django.http import Http404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


class PostCreateView(LoginRequiredMixin, CreateView):
    login_url = 'authors:login_author'
    template_name = 'global/pages/base_form.html'
    model = Posts
    success_url = reverse_lazy('social_echo:home')
    form_class = CreatePost

    def form_valid(self, form):
        form.instance.author = self.request.user

        try:
            author_user = AuthorUser.objects.get(author=self.request.user)
        except AuthorUser.DoesNotExist:
            author_user = None

        if author_user:
            form.instance.author_cover = author_user

        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = 'authors:login_author'
    template_name = 'global/pages/base_form.html'
    model = Posts
    success_url = reverse_lazy('social_echo:home')
    form_class = CreatePost

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)

        if obj.author != self.request.user:
            raise Http404()

        return obj


class PostDeleteView(LoginRequiredMixin, DeleteView):
    login_url = 'authors:login_author'
    template_name = None
    model = Posts
    success_url = reverse_lazy('social_echo:home')

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)

        if obj.author != self.request.user:
            raise Http404()

        return obj

    def get(self, request, *args, **kwargs):
        # só pra ter certeza que ninguém irá
        # excluir como get

        raise Http404()

social_echo/templates/social_echo/pages/dashboard.html
{% extends "global/pages/base.html" %}

{% block content %}
    <div class="dashboard-user-container">
        <div class="dashboard-user">
            {% if cover %}
                <p><img src="{{ cover.url }}" alt="" class="image"></p>
            {% endif %}
            <p>{{ user }}</p>

            <div class="follow_following_dashboard">
                <a href="{% url 'social_echo:list_follows' posts.0.author.id %}">Seguidores: {{ follows }}</a>
                <a href="{% url 'social_echo:list_following' posts.0.author.id %}">Seguindo: {{ following }}</a>
            </div>
            
            {% if request.user.is_authenticated and request.user != user %}
                {% if not user in user_followings %}
                    <a href="{% url 'social_echo:follow_user_system' posts.0.author.id%}" class="follow-btn">Seguir</a>
                {% else %}
                    <a href="{% url 'social_echo:unfollow_user_system' posts.0.author.id%}" class="unfollow-btn">Deixar de seguir</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <div class="main-dashboard-container">
        {% for post in posts %}
            <div>
                <div class="dashboard-container">
                    <div class="dashboard-title">
                        <a href="{% url 'social_echo:edit_post' post.id %}">{{ post.title }}</a>
                    </div>
                    {% if request.user == post.author %}
                        <div class="dashboard-container-button">
                            <a class="button button-dashboard" href="{% url 'social_echo:edit_post' post.id %}">Editar</a>
                            <a class="button button-dashboard" href="{% url 'social_echo:delete_post' post.id %}">Deletar</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

social_echo/templates/social_echo/pages/home.html
{% extends "global/pages/base.html" %}

{% block content %}
    {% include "social_echo/pages/posts.html" %}

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</body>
{% endblock content %}

social_echo/templates/social_echo/pages/list_follows_following.html
{% extends "global/pages/base.html" %}

{% block content %}
    <div class="main-ff-container">
        {% for user in users %}
            <div>
                <div class="ff-container">
                    <div class="ff-title">
                        <p>{{ user }}</p>
                    </div>
                    {% if owner %}
                        <div class="ff-container-button">
                            {% if type_ == 'follows' %}
                                <a class="button button-ff" href="{% url 'social_echo:unfollow_user' user.id %}">Deletar</a>
                            {% elif type_ == 'following' %}
                                <a class="button button-ff" href="{% url 'social_echo:unfollowing_user' user.id %}">Deletar</a>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

social_echo/templates/social_echo/pages/posts.html
{% for post in posts %}
    <div class="post-main">
        <div class="post-author">
            {% if post.author_cover %}
                <img src="{{ post.author_cover.cover.url }}" alt="" class="image">
            {% endif %}
            <p class="author-username">{{ post.author.username }}</p>
        </div>
        <div class="post-content">
            <p class="post-title">{{ post.title }}</p>
            <p class="post-message">{{ post.message }}</p>

            <div class="link-img-post">
                {% if post.cover %}
                    <a href="{{ post.get_absolute_url }}">Veja a imagem...</a>
                {% endif %}
            </div>
            
            {% if request.user == post.author %}
                <div class="button-container">
                    <a class="button" href="{{ post.get_edit_url }}">Editar</a>
                    <form action="{{ post.get_delete_url }}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="button">Deletar</button>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
{% endfor %}

social_echo/templates/social_echo/pages/view_page.html
{% extends "global/pages/base.html" %}

{% block content %}
    <div class="posts-main">
        <div class="posts-author">
            {% if post.author_cover %}
                <img src="{{ post.author_cover.cover.url }}" alt="" class="image-solo">
            {% endif %}
            <p class="author-username-solo">{{ post.author.username }}</p>
        </div>
        <div class="posts-content">
            <p class="post-title">{{ post.title }}</p>
            <p class="post-message">{{ post.message }}</p>

            <div>
                {% if post.cover %}
                    <img src="{{ post.cover.url }}" alt="" class="img_post">
                {% endif %}
            </div>
            
            {% if request.user == post.author %}
                <div class="button-container">
                    <a class="button" href="{% url 'social_echo:edit_post' post.id %}">Editar</a>
                    <a class="button" href="{% url 'social_echo:delete_post' post.id %}">Deletar</a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}